name = "Pav MC"
author = "Zachary"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ae80dcd1ed9306fb0e7b87eb53971ee6b04243e04ea37e679e51a422c7c7173"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
