name = "Pav MC"
author = "Zachary"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8559ab4e5ab31a016df2be96f926a0bf191317da6bed8a0d4ba6e7888565ab4"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
