name = "Pav MC"
author = "Zachary"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72f9ec7a14ee1cd6448bdb96f491778c04163a5887f2e6cd33ad71fd253427f1"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
